spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: lb:http://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**

        - id: packet-service
          uri: lb:http://PACKET-SERVICE
          predicates:
            - Path=/packet/**

        - id: tracking-service
          uri: lb:http://TRACKING-SERVICE
          predicates:
            - Path=/tracking/**
server:
  port: 8222
jwt:
  secret-key: "370c7005cac2e7495f3ee8b6edfe98594e292da208fb21b5d58e63fe064624b3"