version: '3.8'
services:
  config-server:
    build: ./services/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery:
    build: ./services/discovery
    container_name: discovery
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_INSTANCE_HOSTNAME=discovery
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build: ./services/gateway
    container_name: gateway
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    ports:
      - "8222:8222"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://gateway:8222/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword123
      MYSQL_DATABASE: persons
      MYSQL_PASSWORD: P@ssword123
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  authentication:
    build: ./services/authentication
    container_name: authentication
    depends_on:
      discovery:
        condition: service_healthy
      mysql-container:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/persons
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssword123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    ports:
      - "8095:8095"

  packet:
    build: ./services/packet
    container_name: packet
    depends_on:
      discovery:
        condition: service_healthy
      mysql-container:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/tracking
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssword123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    ports:
      - "8090:8090"

  tracking:
    build: ./services/tracking
    container_name: tracking
    depends_on:
      discovery:
        condition: service_healthy
      mysql-container:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/tracking
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssword123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    ports:
      - "8092:8092"

volumes:
  mysql_data: